export const skillsData = {
  sectionOne: [
    {
      skillName: "Introdução",
      skillImg: "egg",
      words: [
        "hello",
        "please",
        "coffee",
        "tea",
        "and",
        "or",
        "yes",
        "milk",
        "water",
        "with",
        "goodbye",
        "no",
        "sugar",
        "thank you",
        `you're welcome`,
      ],
      translation: [
        "olá",
        "por favor",
        "café",
        "chá",
        "e",
        "ou",
        "sim",
        "leite",
        "agua",
        "com",
        "tchau",
        "não",
        "açúcar",
        "obrigado",
        "de nada",
      ],
    },
    {
      skillName: "Saudações",
      skillImg: "speach",
      words: [
        `what's your name`,
        "welcome",
        "hi",
        "good morning",
        "my name is",
        "I am from",
        "and you",
        "Brazil",
        "Canada",
        "thanks",
        "where are you from",
        "portugal",
        "excuse me",
        "good",
        "too",
        "bye",
      ],
      translation: [
        `qual é o seu nome`,
        "Bem-vindo",
        "Oi",
        "bom Dia",
        "meu nome é",
        "eu sou de",
        "e você",
        "Brasil",
        "Canadá",
        "obrigado",
        "De onde você é",
        "Portugal",
        "com licença",
        "Boa",
        "também",
        "tchau",
      ],
    },
    {
      skillName: "Viagem",
      skillImg: "plane",
      words: [
        `what's your name`,
        "welcome",
        "hi",
        "good morning",
        "my name is",
        "i am from",
        "and you",
        "Brazil",
        "Canada",
        "thanks",
        "where are you from",
        "portugal",
        "excuse me",
        "good",
        "too",
        "bye",
      ],
      translation: [
        `qual é o seu nome`,
        "Bem-vindo",
        "Oi",
        "bom Dia",
        "meu nome é",
        "eu sou de",
        "e você",
        "Brasil",
        "Canadá",
        "obrigado",
        "De onde você é",
        "Portugal",
        "com licença",
        "Boa",
        "também",
        "tchau",
      ],
    },
  ],
};
