export const skillsData = {
  sectionOne: [
    {
      skillName: "Introdução",
      skillImg: "egg",
      style: "fullWidth",
      words: [
        "hello",
        "please",
        "coffee",
        "tea",
        "and",
        "or",
        "yes",
        "milk",
        "water",
        "with",
        "bye",
        "no",
        "sugar",
        "thank you",
        `you're welcome`,
      ],
      translation: [
        "olá",
        "por favor",
        "café",
        "chá",
        "e",
        "ou",
        "sim",
        "leite",
        "agua",
        "com",
        "tchau",
        "não",
        "açúcar",
        "obrigado",
        "de nada",
      ],
    },
    {
      skillName: "Saudações",
      skillImg: "speach",
      style: "",
      words: [
        `what's your name`,
        "welcome",
        "hi",
        "good morning",
        "my name is",
        "I am from",
        "and you",
        "Brazil",
        "Canada",
        "thanks",
        "where are you from",
        "Portugal",
        "excuse me",
        "good",
        "too",
        "bye",
      ],
      translation: [
        `qual é o seu nome`,
        "bem-vindo",
        "oi",
        "bom dia",
        "meu nome é",
        "eu sou de",
        "e você",
        "Brasil",
        "Canadá",
        "obrigado",
        "de onde você é",
        "Portugal",
        "com licença",
        "boa",
        "também",
        "tchau",
      ],
    },
    {
      skillName: "Viagem",
      skillImg: "plane",
      style: "",
      words: [
        "a",
        "taxi",
        "I need",
        "passport",
        "hotel",
        "the",
        "where is",
        "airport",
        "bus",
        "train",
        "restaurant",
        "ticket",
        "car",
        "in",
        "is",
        "reservation",
        "help",
        "I have",
        "restroom",
        "to",
      ],
      translation: [
        "um",
        "táxi",
        "preciso",
        "passaporte",
        "hotel",
        "o",
        "onde está",
        "aeroporto",
        "ônibus",
        "trem",
        "restaurante",
        "bilhete",
        "carro",
        "em",
        "é",
        "reserva",
        "ajuda",
        "tenho",
        "banheiro",
        "para",
      ],
    },
    {
      skillName: "Cardápio",
      skillImg: "burger",
      style: "",
      words: [
        "menu",
        "small",
        "large",
        "salad",
        "soup",
        "rice",
        "one",
        "two",
        "dollar",
        "dollars",
        "table",
        "for",
        "three",
        "pizza",
        "pizzas",
        "check",
        "sandwich",
        "I want",
        "four",
        "delicious",
      ],
      translation: [
        "cardápio",
        "pequena",
        "garnde",
        "salada",
        "sopa",
        "arroz",
        "um",
        "dois",
        "dólar",
        "dólares",
        "tabela",
        "por",
        "três",
        "pizza",
        "pizzas",
        "conta",
        "sanduíche",
        "quero",
        "quatro",
        "delicioso",
      ],
    },
    {
      skillName: "Encontros",
      skillImg: "speach",
      style: "",
      words: [
        "Portuguese",
        "speak",
        "English",
        "I",
        "understand",
        "this is",
        "friend",
        "my",
        "your",
        "what",
        "address",
        "phone number",
        "sorry",
        "last name",
        "first name",
        "see you later",
        "good",
      ],
      translation: [
        "Português",
        "falar",
        "Inglês",
        "eu",
        "entender",
        "isto é",
        "amigo",
        "minha",
        "sua",
        "o que",
        "morada",
        "número de telefone",
        "desculpe",
        "sobrenome",
        "primeiro nome",
        "até logo",
        "boa",
      ],
    },
    {
      skillName: "Família",
      skillImg: "child",
      style: "",
      words: [
        "she is",
        "sister",
        "sisters",
        "funny",
        "mother",
        "tall",
        "he is",
        "brother",
        "he has",
        "father",
        "she has",
        "brothers",
        "you have",
        "parents",
        "live",
        "right",
        "is she",
        "family",
        "cat",
        "dog",
        "happy",
      ],
      translation: [
        "ela é",
        "irmã",
        "irmãs",
        "engraçado",
        "mãe",
        "alta",
        "ele é",
        "irmão",
        "ele tem",
        "pai",
        "ela tem",
        "irmãos",
        "você tem",
        "pais",
        "viver",
        "certo",
        "é ela",
        "família",
        "gato",
        "cão",
        "feliz",
      ],
    },
    {
      skillName: "Carreira",
      skillImg: "hat",
      style: "",
      words: [
        "job",
        "an",
        "doctor",
        "artist",
        "office",
        "at",
        "school",
        "teacher",
        "work",
        "are",
        "are you",
        "you",
        "hospital",
        "big",
        "here",
        "wow",
        "very",
        "interesting",
        "supermarket",
        "dentist",
        "bank",
      ],
      translation: [
        "trabalho",
        "um",
        "médico",
        "artista",
        "escritório",
        "em",
        "escola",
        "professora",
        "trabalhar",
        "são/estão",
        "você está",
        "vocês",
        "hospital",
        "grande",
        "aqui",
        "uau",
        "muito",
        "interessante",
        "supermercado",
        "dentista",
        "banco",
      ],
    },
    {
      skillName: "Loja",
      skillImg: "sock",
      style: "fullWidth",
      words: [
        "store",
        "open",
        "closed",
        "new",
        "this",
        "hat",
        "blue",
        "expensive",
        "shirt",
        "shirts",
        "pants",
        "nice",
        "black",
        "how much is",
        "favorite",
        "clothes",
        "shoe",
        "white",
        "red",
      ],
      translation: [
        "loja",
        "aberta",
        "fechado",
        "novo",
        "isto",
        "chapéu",
        "azul",
        "caro",
        "camisa",
        "camisas",
        "calça",
        "legais",
        "preto",
        "quanto é",
        "favorito",
        "roupas",
        "sapato",
        "branco",
        "vermelho",
      ],
    },
    {
      skillName: "Presente 1",
      skillImg: "lightBulb",
      style: "fullWidth",
      words: [
        "are",
        "I",
        "are you?",
        "is",
        "I have",
        "your",
        "is he?",
        "she has",
        "he has",
        "is she?",
        "you have",
        "he is",
        "there is",
        "she is",
        "this is",
        "to work",
        "to live",
        "to understand",
        "to speak",
      ],
      translation: [
        "são/estão",
        "eu",
        "você é/está?",
        "é/está",
        "eu tenho",
        "sua",
        "ele é/está?",
        "ela tem",
        "ele tem",
        "ela é/está?",
        "Você tem",
        "ele é/está",
        "tem",
        "ela é/está",
        "isto é/está",
        "trabalhar",
        "viver",
        "entender",
        "falar",
      ],
    },
    {
      skillName: "Meu dia",
      skillImg: "woman",
      style: "",
      words: [
        "every day",
        "drink",
        "eat",
        "in the morning",
        "bread",
        "roommate",
        "see",
        "friends",
        "we",
        "our",
        "play",
        "soccer",
        "in the afternoon",
        "together",
        "park",
        "a lot",
        "at night",
        "read",
        "watch tv",
        "study",
      ],
      translation: [
        "todo dia",
        "beber",
        "comer",
        "de manhã",
        "pão",
        "colega de quarto",
        "vejo",
        "amigos",
        "nós",
        "nosso",
        "jogar/toque",
        "futebol",
        "a tarde",
        "juntos",
        "parque",
        "muito",
        "à noite",
        "ler",
        "assistir TV",
        "estudar",
      ],
    },
    {
      skillName: "Gostos",
      skillImg: "glasses",
      style: "",
      words: [
        "do you like",
        "like",
        "movie",
        "book",
        "really",
        "love",
        "what",
        "food",
        "music",
        "good",
        "me too",
        "Brazilian",
        "Portuguese",
        "Chinese",
        "do",
        "cook",
        "often",
        "listen to",
        "rock",
        "hip-hop",
        "play the guitar",
        "concert",
      ],
      translation: [
        "você gosta",
        "gostar",
        "filme",
        "livro",
        "realmente",
        "amor",
        "o que",
        "comida",
        "música",
        "bom",
        "eu também",
        "brasileiro",
        "português",
        "chinês",
        "fazer",
        "cozinhar",
        "frequentemente",
        "ouvir",
        "rock",
        "hip-hop",
        "tocar guitarra",
        "show",
      ],
    },
  ],
};
